name: namer_app
description: "go2klo mobile"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gabarito # Dies ist der Name, den wir später im Code verwenden werden
      fonts:
        - asset: assets/fonts/gabarito.ttf